service: lambda-test

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  state: dev
  region: us-east-1
  memorySize: 128
  lambdaHashingVersion: 20201221

functions:
  endpoints:
    handler: src/lambda.endpoints
    events:
      - http:
          path: /endpoints
          method: get
  getZipCode:
    handler: src/lambda.getZipCode
    events:
      - http:
          path: /getLocByZipCode
          method: get
  getCityName:
    handler: src/lambda.getCityName
    events:
      - http:
          path: /getLocByCityName
          method: get
  getNearestLocation:
    handler: src/lambda.getNearestLocation
    events:
      - http:
          path: /getLocByNearestLocation
          method: get
  getAreaCode:
    handler: src/lambda.getAreaCode
    events:
      - http:
          path: /getLocByAreaCode
          method: get
  getTimezone:
    handler: src/lambda.getTimezone
    events:
      - http:
          path: /getLocByStateAndTimezone
          method: get

plugins:
  - serverless-offline
