service: lambda-test

provider:
  name: aws
  runtime: nodejs6.10
  state: dev
  region: us-east-1
  memorySize: 128

functions:
  app:
    handler: src/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-offline