service: lambda-test

provider:
  name: aws
  runtime: nodejs12.0
  state: dev
  region: us-east-1
  memorySize: 128

functions:
  app:
    handler: src/index.handler
    events:
      - http:
          path: src/
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline