service: lambda-test

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  state: dev
  region: us-east-1
  memorySize: 128
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: src/lambda.hello
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  getZipCode:
    handler: src/lambda.getZipCode
    events:
      - http:
          path: /getLocByZipCode
          method: get
  getCityName:
    handler: src/lambda.getCityName
    events:
      - http:
          path: /getLocByCityName
          method: get

plugins:
  - serverless-offline